#!bin/bash

format="%C(yellow)%h%Creset -%Cred%d%Creset %s %Cgreen(%cr)
%C(bold blue)%an%Creset %C(magenta)<%ae>%Creset %C(cyan)%ad%Creset
%C(bold blue)%cn%Creset %C(magenta)<%ce>%Creset %C(cyan)%cd%Creset
"

git log --graph --all --pretty="$format"
